name: Build Blender for Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-2019
    
    steps:
    - name: Checkout Blender source
      uses: actions/checkout@v4
      with:
        repository: blender/blender
        submodules: recursive
        fetch-depth: 0
        
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        # 安装必要的依赖包
        choco install -y git svn cmake ninja
        python -m pip install --upgrade pip
        pip install cython
        
    - name: Set up Visual Studio
      uses: microsoft/setup-msbuild@v2
      
    - name: Configure build
      run: |
        # 创建构建目录
        mkdir build
        cd build
        
        # 运行CMake配置
        cmake ../blender \
          -G "Visual Studio 16 2019" \
          -A x64 \
          -DCMAKE_INSTALL_PREFIX=../install \
          -DCMAKE_BUILD_TYPE=Release \
          -DWITH_PYTHON_INSTALL=ON \
          -DWITH_INSTALL_PORTABLE=ON
          
    - name: Build Blender
      run: |
        cd build
        msbuild /p:Configuration=Release /p:Platform=x64 /m:2 blender.sln
        
    - name: Install build
      run: |
        cd build
        msbuild /p:Configuration=Release /p:Platform=x64 INSTALL.vcxproj
        
    - name: Create zip package
      run: |
        7z a -tzip blender-windows-build.zip ./install/*
        
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: blender-windows-build
        path: blender-windows-build.zip
