name: Build Blender for Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    defaults:
      run:
        shell: cmd  # 使用CMD避免PowerShell的转义问题
    
    steps:
    - name: Checkout Blender source
      uses: actions/checkout@v4
      with:
        repository: blender/blender
        submodules: recursive
        fetch-depth: 0
        path: blender  # 强制源码存放目录为blender
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        choco install -y git svn cmake ninja
        python -m pip install --upgrade pip
        pip install cython
    
    - name: Get precompiled libraries (Windows)
      run: |
        cd blender
        # 运行Blender的更新脚本获取预编译库
        python .\build_files\utils\make_update.py
        # 确保子模块和库都已更新
        git submodule update --init --recursive
    
    - name: Set up Visual Studio
      uses: microsoft/setup-msbuild@v2
    
    - name: Configure build
      run: |
        mkdir build
        cd build
        cmake ..\blender ^
          -G "Visual Studio 17 2022" ^
          -A x64 ^
          -DCMAKE_INSTALL_PREFIX=..\install ^
          -DCMAKE_BUILD_TYPE=Release ^
          -DWITH_PYTHON_INSTALL=ON ^
          -DWITH_INSTALL_PORTABLE=ON
    
    - name: Build Blender
      run: |
        cd build
        msbuild /p:Configuration=Release /p:Platform=x64 /m blender.sln
    
    - name: Install build
      run: |
        cd build
        msbuild /p:Configuration=Release /p:Platform=x64 INSTALL.vcxproj
    
    - name: Create zip package
      run: 7z a -tzip blender-windows-build.zip .\install\*
    
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: blender-windows-build
        path: blender-windows-build.zip
        retention-days: 14
    
